#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)

help_msg <- paste(
  "Usage: validate_outputs.R --parsed-dir PATH --matrix-csv PATH --counts-csv PATH [--report PATH]",
  "",
  "Options:",
  "  --parsed-dir   Directory with GSM*.tsv",
  "  --matrix-csv   Matrix generated by build_snp_matrix.R",
  "  --counts-csv   Counts generated by compute_genotype_counts.R",
  "  --report       Markdown report output",
  "  --help         Show this help",
  sep = "\n"
)

get_arg <- function(flag, default = NULL) {
  i <- which(args == flag)
  if (length(i) == 0) return(default)
  if (i == length(args)) stop(sprintf("Missing value for %s", flag))
  args[i + 1]
}

if ("--help" %in% args || length(args) == 0) {
  cat(help_msg, "\n")
  quit(save = "no", status = 0)
}

parsed_dir <- get_arg("--parsed-dir")
matrix_csv <- get_arg("--matrix-csv")
counts_csv <- get_arg("--counts-csv")
report <- get_arg("--report", "")

if (is.null(parsed_dir) || is.null(matrix_csv) || is.null(counts_csv)) {
  cat(help_msg, "\n")
  quit(save = "no", status = 1)
}

suppressPackageStartupMessages(library(data.table))

gsm_n <- length(list.files(parsed_dir, pattern = "^GSM.*\\.tsv$"))
mat <- fread(matrix_csv, showProgress = FALSE)
cnt <- fread(counts_csv, showProgress = FALSE)

matrix_samples <- max(0, ncol(mat) - 1)
matrix_snps <- nrow(mat)
counts_snps <- nrow(cnt)
nonzero_rows <- sum(cnt$n > 0, na.rm = TRUE)

lines <- c(
  "# Pipeline QC report",
  "",
  sprintf("- parsed GSM tables: %d", gsm_n),
  sprintf("- matrix samples: %d", matrix_samples),
  sprintf("- matrix SNP rows: %d", matrix_snps),
  sprintf("- counts SNP rows: %d", counts_snps),
  sprintf("- counts rows with n>0: %d", nonzero_rows)
)

cat(paste(lines, collapse = "\n"), "\n")

if (nzchar(report)) {
  dir.create(dirname(report), recursive = TRUE, showWarnings = FALSE)
  writeLines(lines, report)
}
